name: upi_fees_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.1
  syncfusion_flutter_pdf: ^32.1.25
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#4F46E5" # Indigo color matches our theme
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
